Revert "Bump maven-war-plugin from 3.2.2 to 3.3.1 (#481)"
This reverts commit f6423903d7e2c2a0e29ba824e739d1652feacf9c.

This was causing the tomcat dev environment to fail to start with a
ClassNotFoundException: org.springframework.web.context.ContextLoaderListener